---
# tasks file for nutanix_role_prism_container
  - name: Inputs for remove default container task
    include_tasks: remove_default_container.yml
    when: prism_containers_remove_default

  - name: Include default variables
    ansible.builtin.include_vars:
      file: vars/defaults.yml

  - name: Inputs for set container task
    include_tasks: set_container.yml
    loop: "{{ prism_containers_list }}"
    loop_control:
      loop_var: outer_item
