---
# tasks file for nutanix_role_nutanix_container
- import_tasks: setup_api.yml

- name: "Task can only be run against Prism Element"
  ansible.builtin.fail:
    msg: "{{nutanix_host}} is not a Nutanix cluster. Please check the nutanix_host variable and try again."
  when:
    - nutanix_endpoint_prism_type != 'pe'

- name: Inputs for remove default container task
  include_tasks: remove_default_container.yml
  when: nutanix_containers_remove_default

- name: Include default variables
  ansible.builtin.include_vars:
    file: vars/defaults.yml

- name: Inputs for create/update container task
  include_tasks: crud_container.yml
  loop: "{{ nutanix_containers_list }}"
  loop_control:
    loop_var: outer_item
