---
  - name: Inputs for get containers task
    include_tasks: get_containers.yml

  - name: Gather default container uuid
    set_fact:
       nutanix_default_container_uuid: "{{item}}"
    with_items: "{{ nutanix_current_containers.json | to_json | from_json | json_query(query) }}"
    vars:
       query: "entities[?contains(name, 'default-container-')].storage_container_uuid"
    when: nutanix_current_containers.json.metadata.total_entities > 0

  - name: Delete default container
    uri:
      url: "{{ nutanix_api_v2 }}/storage_containers/{{ nutanix_default_container_uuid }}"
      method: DELETE
      validate_certs: "{{ validate_certs }}"
      body_format: json
      headers:
        Authorization: "{{ nutanix_api_auth }}"
      status_code: 204
      return_content: yes
    register: nutanix_delete_default_container
    ignore_errors: no
    when: nutanix_default_container_uuid is defined

  - name: Debug remove_default_container.yml variables
    debug:
      var: "{{ item }}"
    loop:
      - nutanix_default_container_uuid
      - nutanix_delete_default_container.json
    when:
      - nutanix_debug
